version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: jobsDb
    restart: always
    environment:
      - MYSQL_DATABASE=jobsDb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3307:3306'
    networks:
      - job

  app:
    build: ./
    container_name: jobs-app
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://jobsDb:3306/jobsDb?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=password
      - webdriver.run.in.docker=true
      - webdriver.chrome.host=selenium-chrome
    depends_on:
      - db
      - chrome
    networks:
      - job

  chrome:
    image: selenium/standalone-chrome:114.0-chromedriver-114.0
    container_name: selenium-chrome
    ports:
      - "4444:4444"
    networks:
      - job

networks:
  job:
    driver: bridge
