version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: jobsDb
    restart: always
    environment:
      - MYSQL_DATABASE=jobsDb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3307:3306'
    networks:
      - job

  app:
    build: ./
    container_name: jobs-app
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://jobsDb:3306/jobsDb?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=password
    depends_on:
      - db
    networks:
      - job

networks:
  job:
