version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: jobsDb
    environment:
      - MYSQL_DATABASE=jobsDb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3307:3306'
    networks:
      - job


networks:
  job:
